### ISSUE TITLE
I get can not parse for all ovpn files..

### ISSUE THREAD

**Issue by ghost** [underscoredam/nordvpn-speedtest-benchmark#1]

**Comment by damo-da** [comment]
I don't know why that's happening. One of the things to note is that I'm working for TCP servers only and maybe that's the reason why only half of the servers are evaluated. I'm ignoring <server>.udp.conf because I'd expect it to be linearly propertional to <server>.tcp.conf

**Comment by ghost** [comment]
I just removed all the .udp.conf files from the folder and it still does it. Theres no other errors besides  the "can not parse for"

**Comment by damo-da** [comment]
may I know how many files/servers can the script not parse for? Or some specific servers that it is not parsing for?

**Comment by ghost** [comment]
It says it cant parse any of them.. It goes through the whole list and just says it can not parse.

**Comment by damo-da** [comment]
did you modify the SCRIPTS_DIR on `best_server.py`? That needs to be the directory (preferred if from root path) where all your ovpn files are.

**Comment by ghost** [comment]
Yeah I did, I put them in a folder called "configs" and changed the SCRIPTS_DIR to the complete path.

This is from the command promt. http://pastebin.com/PdizbGuP

**Comment by damo-da** [comment]
Which platform are you using? Also, it's working properly on my laptop. Let's do the following: 

* Import `traceback` module. To do this, add a line "import traceback" after "import re"
* Change the line "except Exception" to "except Exception as e"
* Then print the stacktrace by adding `traceback.print_exc()` after `print("Can not parse for {}".format(f))` on the `escape` case? 

Here's what the script is going to look like: 
http://pastebin.com/9zDRgVUq

**Comment by ghost** [comment]
Im currently using Windows 10 with Python 3.

Its now putting out this http://pastebin.com/btMqFWhe

**Comment by damo-da** [comment]
Ah, that's because I didn't give much attention to Windows. Anyways, I think [this script](http://pastebin.com/SGBqLneL) should fix it. Let me know if this works, otherwise I'll fix this up tomorrow. Merry Christmas!

**Comment by damo-da** [comment]
Basically, I changed /bin/ping to ping.exe in case the os is windows.

**Comment by ghost** [comment]
It gave the same error as before and yeah I noticed the change. Merry Christmas to you too :)

**Comment by ghost** [comment]
Just as a cool idea. You could always make it that it finds the fastest VPN then connects to it through OpenVPN. Just an idea haha

**Comment by kleerkoat** [comment]
i'm having the same parsing error as well on Mac.

**Comment by damo-da** [comment]
Sorry it took so long but I've finally fixed the issue on Mac as Well as windows. For `ping` command, I was using `/usr/bin/ping` which is the wrong path on Mac (and Windows). Fixed on [this commit](7e21400). I'm now going to close the issue. Let me know if you encounter any problems.
